quarkus.index-dependency.rimfrost-regel.group-id=se.fk.rimfrost.framework.regel
quarkus.index-dependency.rimfrost-regel.artifact-id=rimfrost-framework-regel

quarkus.index-dependency.rimfrost-framework-regel-oul.group-id=se.fk.rimfrost.framework.regel.oul
quarkus.index-dependency.rimfrost-framework-regel-oul.artifact-id=rimfrost-framework-regel-oul

quarkus.hibernate-validator.method-validation.allow-overriding-parameter-constraints=true

#Outgoing
mp.messaging.outgoing.regel-responses.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.regel-responses.connector=smallrye-kafka
